name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker pull image
        run: docker pull aniket2525/equal-expert-assignment1:v1

      - name: Build Docker image
        run: docker build -t aniket2525/equal-expert-assignment1:v2 .

      - name: Push Docker image
        run: docker push aniket2525/equal-expert-assignment1:v2

  run_and_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo This is the final output
